-- 1
create or replace function verifica_cpf() returns trigger as
$$
begin
	if (TG_OP = 'INSERT') then
		if exists (select 1 from cliente where cpf = new.cpf) then
			raise exception 'CPF ja existe';
		end if;
	elsif (TG_OP = 'UPDATE') then
		if (select count(*) from cliente where cpf = new.cpf) > 0
			and old.cpf <> new.cpf then
				raise exception 'CPF ja existe';
		end if;
	end if;
	return new;
end;
$$
language plpgsql;

create trigger verifica_cpf before insert or update
	on cliente for each row execute procedure verifica_cpf()

-- insert into cliente values (8, '10000110011', 'Teste 1', 20, 'Rua Lages', 'Jlle')

update cliente set idade = 24
	where codc = 8
	
select * from cliente

-- 2
-- Onde: mecanico
-- Quando: before
-- Operacoes: insert ou update
-- Nivel: row level

create or replace function verifica_idade() returns trigger as
$$
begin
	if new.idade < 20 then
		raise exception 'Mecanico nao pode ter menos de 20 anos';
	end if;
	return new;
end;
$$
language plpgsql;

create trigger verifica_idade before insert or update
	on mecanico for each row execute procedure verifica_idade()

select * from meccanico

-- insert into mecanico values(6, '11000111011', 'Teste 1', 25, 'Rua Lages', 'Joinville', 'Pintor', 1)

-- 3
create sequence seq_cods; -- faltava criar a sequence

create or replace function new_cods() returns trigger as
$$
begin
	new.cods := nextval('seq_cods');
	return new;
end;
$$
language plpgsql;

create trigger new_cods before insert on setor
	for each row execute procedure new_cods();


select * from setor

-- insert into setor (nome) values ('Teste 2')

-- 4
-- Onde: mecanico e cliente
-- Quando: before
-- Operacoes: insert or update
-- Nivel: row level

create or replace function valida_cpf() returns trigger as
$$ 
begin
	if not validaCPF(new.cpf) then
		raise exception 'CPF invalido';
	end if;
	return new;
end;
$$
language plpgsql;

create trigger valida_cpf_mecanico before insert or update
	on mecanico for each row execute procedure valida_cpf();

create trigger valida_cpf_cliente before insert or update
	on cliente for each row execute procedure valida_cpf();

-- 5
-- Tabela: mecanico
-- Quando: before
-- Operacoes: delete
-- Nivel: row level

create or replace function remove_mecanico() returns trigger as
$$
begin
	if (select count(*) from mecanico where funcao ilike old.funcao) <= 1 then
		raise exception 'Unico mecanico da funcao nao pode ser excluido';
	end if;
	return old;
end;
$$
language plpgsql;

create trigger remove_mec before delete on mecanico
	for each row execute procedure remove_mec();

select * from mecanico

delete from mecanico where codm = 11

-- 6
-- Tabela: mecanico
-- Quando: after
-- Operacoes: delete
-- Nivel: row level

create sequence seq_codc start 10;

alter table cliente
	alter column codc add generated by default as identity
	
create or replace function atualiza_cliente() returns trigger as
$$
begin
	if(TG_OP = 'INSERT' or TG_OP = 'UPDATE') then
		if(select count(*) from cliente
			where cpf = new.cpf) > 0 then
				update cliente set
					nome = new.nome,
					idade = new.idade,
					endereco = new.endereco,
					cidade = new.cidade
				where cpf = new.cpf;
			else 
				insert into cliente values (null, new.cpf, new.nome, new.idade, new.endereco, new.cidade);
			end if;
			return new;
	elsif (TG_OP = 'DELETE') then
		delete from cliente where cpf = old.cpf;
		return old;
	end if;
	return null;
end;
$$
language plpgsql;

select * from cliente

insert into cliente (nome) values ("teste")
delete from cliente where codc = 10

create trigger atualiza_cliente after insert or update or delete on mecanico for each row execute procedure atualiza_cliente();

select * from cliente
select * from mecanico

--insert into mecanico values (null, '22668151058', 'Teste 10', 30, 'Rua Tijucas', 'Joinville', 'Lavador', 2)

-- update mecanico set endereco = 'Garuva' where codm = 11

-- delete from mecanico where codm = 10

-- 7
create or replace function calculaHoraExtra(pcodm int, pmes int, pano int) returns int as
$$
declare
	horasTrab integer default 0;
begin
	select count(*) into horasTrab
	from conserto
	where codm = pcodm
	  and date_part('month', date) = pmes
	  and date_part('year', date) = pano;
	if horasTrab > 3 then
		return horasTrab - 3;
	else
		return 0;
	end if;
end;
$$
language plpgsql;

create or replace function calcula_alocacao() returns trigger as
$$
begin
	if (TG_OP = 'INSERT') and (calculaHoraExtra(new.codm, date_part('month', new.data)::int, date_part('year', new.data)::int) > 1) then
		raise exception 'Mecanico excedeu horas extras';
	elsif (TG_OP = 'UPDATE') and (new.codm <> old.codm) then
		if calculaHoraExtra(new.codm, date_part('month', new.data)::int, date_part('year', new.data)::int) > 1 then
			raise exception 'Mecanico excedeu horas extras';
		end if;
	end if;
	return new;
end;
$$
language plpgsql;

create trigger calcula_alocacao before insert or update on conserto
for each row execute procedure calcula_alocacao();

--insert into conserto values (1,2, '17/09/2025', '10:00:00')

-- 8
create or replace function verifica_conserto_setor() returns trigger as
$$
begin
    if exists (
        select 1
        from conserto
        where cods = new.cods
          and data = new.data
          and hora = new.hora
          and (TG_OP = 'INSERT' or (TG_OP = 'UPDATE' and codn <> old.codn))
    ) then
        raise exception 'Ja existe um conserto agendado nesse setor nesta data e hora';
    end if;
    return new;
end;
$$
language plpgsql;

create trigger verifica_conserto_setor
    before insert or update on conserto
    for each row execute procedure verifica_conserto_setor();
